### PR TITLE
Join Ordering: Layered Search 

### PR DESCRIPTION
**Pull request by david990917**
Dear Mutable Team,

My branch contains naive code for expanding the join ordering heuristic search.  For now, the layered search is a stable algorithm and could sometimes achieve **better cost than IKKBZ and even less plan time**.

There are also Bidirectional Searches and IDA*, which are under development.  

If possible please give me feedback and advice, and I will do it immediately :) And after the code logic is fixed, I would like to adjust the code to latest style and merge it if needed.

### CODE REVIEW

**Comment by david990917** [comment]
The current code structure and git commit history are a little bit chaotic, I will fixed them

**Comment by david990917** [comment]
You can run the `bash hanwen-eval-planners.sh ` or directly within the shell 

`--quiet --dryrun --times --plan-table-las --plan-enumerator HeuristicSearch --hs-vertex SubproblemsArray --hs-expand BottomUpComplete --hs-heuristic zero --hs-search hanwen_layered_search --cardinality-estimator Injected --use-cardinality-file star-5.cardinalities.json --statistics star-5.schema.sql star-5.query.sql`

**Comment by ImmanuelHaffner** [comment]
Thanks for the PR. I will try to give it a review. I'm currently very busy though. Also, the PR is really messy. There are 50(!) modified files and you are basically filing multiple features for PR at once.
I would certainly appreciate a cleanup and bringing this branch up-to-date with `main`. If it's not too much to ask for, perhaps we can even split this into multiple PRs: one per search algo?

**Comment by david990917** [comment]
Dear Immanuel, I will try to improve the code and logic. Hope I can get back to you soon.

**Comment by ImmanuelHaffner** [comment]
I just realized that the `pr-target` branch was completely out of date. The updates must be failing. I will investigate. For now, I just updated `pr-target` manually.

I browsed through your changes and immediately spottet a big problem! It seems that your IDE changed the formatting in many places. I see spurious empy lines, new code indents, line wraps, spaces removed before ampersand (`Type &obj` becomes `Type& obj`). These changes are not acceptable!
First of all, we have a relatively strict code format / style. The current state of the PR does not satisfy them.
Second, such changes are harmful because they bloat the PR / commits, and thereby make it harder to understand the *semantic* change by the PR/commits.
Third, such changes do change the ownership of certain lines of code. This is bad, as it makes it harder to find the actual author of a certain algorithm or data structure.

Please do take care of these issues. I suggest that you make yourself familar with the formatting settings of your IDE. It's usually possible to make *per-project* configurations. Configure your IDE to adhere to mu*t*able's format, or at least not to modify existing lines of code. When done, I suggest that you revert such changes in your PR. You can do so interactively patch by patch with `git restore -p` (see `git help restore`).

**Pull request closed without merging**
