### PR TITLE
Fix the small bug in the unittest

### PR DESCRIPTION
**Pull request by david990917**
Dear Mutable Team, I love your paper and open-source repo very much.

During the unit test, I found only this small test - `"Table empty access"` can not pass, I fix it. 

Great thanks for your project and I wish you all the best with your research.

### CODE REVIEW

**Comment by ImmanuelHaffner** [comment]
Hey David,

I am glad you like mu_t_able :) Thanks for providing this fix. I will be happy to merge it, but there is a tiny thing missing. Our unit tests have tags and tag `[core]` is necessary for tests that _must_ pass. Therefore, plase add the tags `[core][catalog][schema]` to the `TEST_CASE("Table empty access")` in your MR. Then it will run as part of our CI.

It seems like I simply forgot to add the tags to this test case.

Your contribution is appreciated! Feel free to send me a mail to get in touch in case you want to know something about mu_t_able or our research. If you are using / evaluating mu_t_able, then please let me know, I'm curious ;)

Regards,
Immanuel

**Comment by david990917** [comment]
Dear @ImmanuelHaffner,

I have already added the tag.

**Comment by ImmanuelHaffner** [comment]
Looking good! Now here's how you go about getting this merged:

1. Make sure you have commit signing enabled. We changed our policy some time ago to enforce commit signing.
2. Perform a rebase to our current `main`. Thereby, the merges from `main` into your branch will be dropped. This is a good thing. I recommend to create a local backup of your branch (`$ git branch backup`), in case things go wrong.
3. Perform an _interactive_ rebase to our `main`. This will allow you to _reword_ `r` your commit messages. (After step 1, there should only be 2 commits left.) Please add at the very first line of each commit message a commit tag, i.e. here `[UTest]`. This will later help identify commits of interest in the log. Furthermore, while rewording, please try to give a precise yet brief explanation of your changes: What motivated your edit? What did you do conceptually? Why did you choose these particular changes? (All rather trivial stuff for this PR.)
4. Force-push your changes to your PR branch. This should then immediately update this PR.

I know this sounds like a lot, but it's really just small stuff. We at mu*t*able want to keep our code base and log as clean as possible. Commit tags help a lot. Avoiding superfluous merge commits on the `main` branch also helps tremendously. Commit signing creates a higher level of trust than just `git blame` :P 

Let me know if something is unclear. Looking forward to merging your PR.

**Comment by david990917** [comment]
Dear @ImmanuelHaffner ,

I think it works now.

If there is anything else to do, please let me know. Enjoy the contributing process.

**Comment by ImmanuelHaffner** [comment]
Looks very good now! One last thing: upload the public part of your signing key to your GitHub account. After doing so, you can inspect that your commits appear as "Verified".  The current status is "Unverified", meaning that commits were signed but there is no trusted connection between the signing key and your GitHub account.

**Comment by david990917** [comment]
Got it, I will check it again. I have already uploaded, it is a little bit wierd.

**Comment by david990917** [comment]
Solved.

**Comment by ImmanuelHaffner** [comment]
Thanks a bunch! Your contribution is appreciated :)

It is merged now. However, I ran into issues. Somehow, the commit was not signed. I signed it myself now and submitted your PR to our internal CI. Should be through in roughly 1 hour. I think you only set up to be a verified GitHub user, i.e. the mail used in Git commit authorship is one of the mail addresses linked to your GitHub account. You still should enable Git commit signing ;)

For future PRs through GitHub, I will have to find a more robust and simpler process. Perhaps we provide a separate branch for pull requests to go to. Then we can pull from that PR branch into our GitLab instance and merge to `main` there. We will have to see...

All the best to you!

**Comment by ImmanuelHaffner** [comment]
@david990917 your PR made it into release 0.0.34, congrats :P 
Having GitHub PRs go to `main`, however, does cause some troubles. I'll see that we find a better workflow for future PRs ;)

**Pull request merged**
